Only display default credit info if FSE is not active.
Automattic/themes pull request #1612
Opened 2019-10-30 23:33 UTC by noahtallen

We'll be using the FSE footer credit block instead.

**Note: This should NOT be deployed until the footer credit is included on WordPress.com.**

### Changes:
- Move footer credit structure inside if statement which runs if FSE is not active. 

### Testing:
1. Pull these changes to your local FSE setup.
2. The footer credit will no longer show up if FSE is active.
3. The footer credit will show up if FSE is inactive.
4. You can use the footer credit block from the below PR. If you put it in the footer, it should look identical to the implementation we are moving in this PR.

#### Related issue(s): https://github.com/Automattic/wp-calypso/pull/37012

2019-10-31 15:16 UTC, Copons requested changes
I think you have moved the `site-info` into the wrong conditional block 😅 

It's inside this:
https://github.com/Automattic/themes/blob/dde2d7c8af88a24252a9793f6583c89e4f68701a/varia/footer.php#L26-L38

But instead it should go at the end of this:
https://github.com/Automattic/themes/blob/dde2d7c8af88a24252a9793f6583c89e4f68701a/varia/footer.php#L23-L39

2019-10-31 19:53 UTC, noahtallen commented
Ah great catch! Does 34c3287 look right?

2019-10-31 21:30 UTC, noahtallen commented on maywood/style.css
> + * Business Hours
These changes must not have been rebuilt at some point

2019-11-01 11:25 UTC, Copons approved these changes
Changes in `footer.php` LGTM!

Though, there are some SCSS changes going on at the moment with the Varia themes, that might break stuff unexpectedly.
Since this change does not have any styling changes, do you mind removing the CSS files from the PR before merging?

2019-11-01 19:02 UTC, noahtallen commented
@copons those are expected style changes (I updated the PR description and left a comment) which simply removes an FSE override for the footer credit area. This shouldn’t break anything since that style only existed if FSE was active.

However you do bring up a good point. Should we just wait to merge until the Dotcom integration of the footer credit block is ready? If we merge this and then deploy varia, current FSE sites won’t see a footer credit area.
On Nov 1, 2019, 4:25 AM -0700, Jacopo Tomasone <notifications@github.com>, wrote:
> @Copons approved this pull request.
> Changes in footer.php LGTM!
> Though, there are some SCSS changes going on at the moment with the Varia themes, that might break stuff unexpectedly.
> Since this change does not have any styling changes, do you mind removing the CSS files from the PR before merging?
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-11-01 19:15 UTC, Copons commented
@noahtallen Ah, you're right, there are a few unrelated CSS changes but also related ones, sorry about it.

Anyway, yes let's wait for the Site Credit block, and deploy in sync! 👍

2019-11-05 14:40 UTC, vindl approved these changes

2020-05-19 18:57 UTC, noahtallen commented
this will be superseded by proper FSE themes.

2020-05-19 18:57 UTC, closed without merging