Dara: Fix meta overflow issue
Automattic/themes pull request #1788
Opened 2020-02-08 05:56 UTC by nielslange

Fixes #1787 

<table>
<tr>
<td>Before:

![#1787-before](https://user-images.githubusercontent.com/3323310/74080029-840afe80-4a7a-11ea-9505-7cc2da3e964d.png)
</td>
<td>After:

![#1787-after](https://user-images.githubusercontent.com/3323310/74080025-75bce280-4a7a-11ea-8321-85d2ba11cfbe.png)
</td>
</tr>
</table>

2020-02-13 16:07 UTC, danieldudzic requested changes
Fix targets `.entry-meta` which is overbroad and breaks post meta styling for regular posts. Please add a Gutenberg specific fix.

2020-02-14 04:55 UTC, nielslange commented
> Fix targets `.entry-meta` which is overbroad and breaks post meta styling for regular posts. Please add a Gutenberg specific fix.

@danieldudzic As requested, I've adjusted this PR and you can find the Gutenberg specific fix in https://github.com/Automattic/themes/pull/1788/commits/1100c65ea57ccab342a4fd689c1ac339119097d3. 😀

2020-03-03 11:19 UTC, danieldudzic requested changes
Would you mind also adding additional styling for the post meta - so that all of it displays correctly - mirroring the editor?

![meta](https://user-images.githubusercontent.com/905781/75770907-2f8d3300-5d49-11ea-8f4e-9c8a78529661.png)

2020-03-24 16:55 UTC, danieldudzic approved these changes

2020-03-24 16:55 UTC, merged