Brompton: Bottom of Site Header is Covered When Cover Block has Transparency Effect Applied
Automattic/themes pull request #2302
Opened 2020-07-29 18:19 UTC by edequalsawesome

#### Changes proposed in this Pull Request:
Added CSS to the `_extra-child-theme.scss` file to set a `z-index` for a Cover block that has a overlay with it, which currently goes over the bottom portion of the site header:

[![Before CSS](https://d.pr/i/4nNojF+)](https://d.pr/i/4nNojF)

With the CSS applied, the site header behaves as expected:

[![After CSS](https://d.pr/i/DUq7C6+)](https://d.pr/i/DUq7C6)

#### Related issue(s):

#2184

2020-11-04 12:04 UTC, MaggieCabrera requested changes
This works fine for me but it needs to run npm run build first (the build files should also be committed to the PR)

2020-11-04 18:02 UTC, scruffian commented
I pushed a different approach to this and rebuild the CSS if you wouldn't mind reviewing again. Thanks!

2020-11-06 15:26 UTC, scruffian commented
I think its better to apply the fix to the masthead.

2020-11-06 15:28 UTC, scruffian commented
This will get deployed later when we deploy all varia themes...

2020-11-06 15:28 UTC, merged