Spearhead posts excerpts styles
Automattic/themes pull request #2575
Opened 2020-10-09 15:23 UTC by MaggieCabrera

#### Changes proposed in this Pull Request:

This provides styles for the excerpt of the posts both on the front page and the archives/category pages.

* Changed the "More" link to fit the design
* Removed the Seedlet footer links for the excerpts.

#### Related issue(s):

#2524

2020-10-09 18:54 UTC, jffng reviewed
This looks good to me!

My only comment is I wonder we should place an ellipsis between the excerpt text and the "More" link? It's a little abrupt to go straight from the text to the "More" button.

<img width="770" alt="Screen Shot 2020-10-09 at 2 53 27 PM" src="https://user-images.githubusercontent.com/5375500/95621139-3991b580-0a3f-11eb-8473-094ff81a9715.png">

2020-10-12 17:01 UTC, scruffian commented
I found a couple of issues with this approach:

<img width="1440" alt="Screenshot 2020-10-12 at 17 59 55" src="https://user-images.githubusercontent.com/275961/95772561-d6a95400-0cb4-11eb-8d79-cb498e2d00da.png">
<img width="888" alt="Screenshot 2020-10-12 at 17 59 36" src="https://user-images.githubusercontent.com/275961/95772566-d90bae00-0cb4-11eb-84e3-38415c08eaf9.png">

I have a solution in mind for this, I'm just testing it

2020-10-12 17:01 UTC, scruffian requested changes
See screenshots above

2020-10-13 15:06 UTC, scruffian commented
This is ready for another review

2020-10-13 16:20 UTC, jffng reviewed
This is looking good! I found one issue with the hover state of the more link:

![Kapture 2020-10-13 at 12 10 26](https://user-images.githubusercontent.com/5375500/95887864-58998b80-0d4e-11eb-8e3d-378cbbcabc43.gif)

Looks like it briefly gets an underline and changes the height of the element when the mouse leaves the target hover area.

2020-10-13 16:20 UTC, jffng commented on spearhead/template-parts/content/content-excerpt.php
> + * @package Seedlet
```suggestion
 * @package Spearhead
```

2020-10-13 16:26 UTC, kjellr commented
I may have missed the discussion, but I see that this isn't inlined anymore. Was that idea abandoned? 

In any case, can we shrink the text size of the read more link to match the excerpt? We should also add an underline on hover to this link. 

Not sure if it's just that this PR is out of date, but I see this error when loading a post that uses the Latest Posts block. I don't see it on Master: 

![Screen Shot 2020-10-13 at 12 20 44 PM](https://user-images.githubusercontent.com/1202812/95888357-fee59100-0d4e-11eb-806e-26e74b38c622.png)

2020-10-13 16:32 UTC, MaggieCabrera commented
> Looks like the height of the element changes when the mouse enters the target hover area, and briefly gets an underline when the mouse leaves the target area.

This is actually a border, I believe: 

https://github.com/Automattic/themes/blob/68196181c6efc7d0488a9b5b69ca8b4aa7b1f7dd/spearhead/assets/sass/_text.scss#L2

2020-10-13 16:34 UTC, jffng commented
> I may have missed the discussion, but I see that this isn't inlined anymore. Was that idea abandoned?

It should still be inline, only when you add a "Read More" block would it appear on its own line.

> Not sure if it's just that this PR is out of date, but I see this error when loading a post that uses the Latest Posts block. I don't see it on Master:

I'm unable to reproduce this error. I did have to delete the branch and check it out fresh before I could view the latest changes.

2020-10-13 19:22 UTC, jffng commented
> can we shrink the text size of the read more link to match the excerpt?

The text sizes should match when a read more block is used, and it's actually a little smaller for the category / archive pages. Should they match? 

<img width="886" alt="Screen Shot 2020-10-13 at 3 19 28 PM" src="https://user-images.githubusercontent.com/5375500/95906007-8dfea300-0d67-11eb-9e34-138d03564f35.png">

> We should also add an underline on hover to this link.

👍

2020-10-14 09:35 UTC, scruffian commented
This is looking good to me. @kjellr if you have more changes we'll follow up in a future PR. Thanks!

2020-10-14 09:35 UTC, merged

2020-10-14 11:32 UTC, kjellr commented
@jffng: 

> The text sizes should match when a read more block is used, and it's actually a little smaller for the category / archive pages. Should they match?

Yeah, I think we should use the same size everywhere. For consistency's sake, maybe we try using the same font size as the post meta?