Seedlet: Add underline to comment author/edit links on hover
Automattic/themes pull request #3339
Opened 2021-02-23 16:28 UTC by danieldudzic

Closes #3330

2021-02-23 17:50 UTC, scruffian commented on seedlet/assets/sass/style.scss
> +Version: 1.1.10-wpcom
Shouldn't this go up?

2021-02-23 17:55 UTC, scruffian commented on seedlet/assets/sass/components/comments/_comment-form.scss
>  		border-bottom: none;
I wonder if we should just remove this line, so the behaviour is the same as on the rest of the theme, i.e. the link is underlined until it's hovered.

2021-02-23 17:56 UTC, scruffian requested changes
I think we should make the behaviour consistent with the rest of the theme, and hide the underline on hover, but we should probably get a second opinion from @kjellr

2021-02-24 13:09 UTC, kjellr reviewed
> I think we should make the behaviour consistent with the rest of the theme, and hide the underline on hover, but we should probably get a second opinion from @kjellr

I prefer it this way (underline only appears on hover) for utility links that appear close together like these ones do. We already do this for post meta. 👍 

The only issue I see in this PR is that the author link should be green on hover, just like the other links: 

![hover](https://user-images.githubusercontent.com/1202812/109005146-9f41af80-7677-11eb-996f-5f561dfa8576.gif)

Once that's fixed, this should be good to go.

2021-02-24 14:57 UTC, kjellr commented
I just pushed a quick update sync up with `trunk` and also cover that text color:

![hover](https://user-images.githubusercontent.com/1202812/109019154-b9cf5500-7686-11eb-9c9c-94a575ac6e0d.gif)

Should be all set, if someone can give it one last review.

2021-02-24 17:34 UTC, scruffian approved these changes
LGTM

2021-02-24 17:50 UTC, merged