Dalston: Separate script and style enqueues for better performance
Automattic/themes pull request #3830
Opened 2021-05-11 16:37 UTC by sixhours

#### Changes proposed in this Pull Request:

* Use separate functions with separate hooks for enqueuing styles and scripts in Dalston to avoid unnecessary enqueues on the front end.
* Props to @westonruter for the bug report and original fix in #1652 

This doesn't appear to break anything in my testing, but I could use a Theam review to confirm things are still working as expected. I'm not sure what the block customizations are supposed

2021-05-11 18:13 UTC, westonruter requested changes

2021-05-11 18:13 UTC, westonruter commented on dalston/functions.php
> +
This shouldn't be needed as it is only relevant when enqueuing scripts, since custom scripts enqueued in this way are not AMP-compatible. Stylesheets on the other hand _are_ compatible, so they should be retained on AMP to ensure proper styling.

```suggestion
```

2021-05-11 18:42 UTC, sixhours commented on dalston/functions.php
> +
Thank you!! Updated :)

2021-05-17 21:19 UTC, kwight commented
@sixhours How are we testing these?..

2021-05-18 14:39 UTC, sixhours commented
> @sixhours&nbsp;How are we testing these?..

Oops! Added some testing instructions. :)

2021-06-01 16:52 UTC, kwight commented
Great! I synced this branch to my sandbox and switched to Dalston, and found the stylesheets only on the front-end, and both the stylesheets and the scripts loaded in the editor.

2021-06-01 16:53 UTC, kwight approved these changes
:shipit:

2021-06-01 18:43 UTC, merged

2021-06-01 18:43 UTC, sixhours commented
Synced in r59024-wpcom-themes