Add: Zoologist and update from Geologist
Automattic/themes pull request #4817
Opened 2021-10-12 10:02 UTC by scruffian

#### Changes proposed in this Pull Request:
This adds the Zoologist code from wpcom and updates it with the latest changes from Geologist.

2021-10-12 13:36 UTC, pbking commented
Looks groovy to me as far as I can tell.  I'll leave a final sign off to @alaczek

2021-10-13 01:20 UTC, alaczek commented on zoologist/child-theme.json
> -					"size": "16px",
I made these font-size changes on purpose, to match the design in Figma, so I'd like to keep them in place.

2021-10-13 01:21 UTC, alaczek commented on zoologist/child-theme.json
> -					"size": "18px",
I made these font-size changes on purpose, to match the design in Figma, so I'd like to keep them in place.

2021-10-13 01:25 UTC, alaczek commented on zoologist/child-theme.json
> -				"spacing": {
I made this change on purpose. Zoologist uses Query block on the home page, and some spacing is needed between the post title and the content. 
I'm actually wondering if this is a Geologist issue? Take a look at this site using Geologist where the Home page is set using Query block https://zoologiststarter.wordpress.com/, and compare to Geologist demo https://geologistdemo.wordpress.com/ that uses the "Display posts on front" setting in the Customizer.

2021-10-13 01:25 UTC, alaczek commented on zoologist/child-theme.json
> -					"fontWeight": 700,
I made this change on purpose, to match the design in Figma, so I'd like to keep it in place.

2021-10-13 01:27 UTC, alaczek requested changes
I left some inline code comments - tl;dr is I made some design changes in Zoologist on purpose and I'd like to keep them.

2021-10-13 01:29 UTC, alaczek commented on blockbase/rebuild-child-themes.sh
> +declare -a ChildThemes=( "mayland-blocks" "seedlet-blocks" "quadrat" "skatepark" "geologist" "videomaker" "zoologist" )
Can you explain what this does exactly? :) 
We're planning to generate a few more themes from Blockbase, do I need to add them here as well?

2021-10-13 07:31 UTC, MaggieCabrera commented on blockbase/rebuild-child-themes.sh
> +declare -a ChildThemes=( "mayland-blocks" "seedlet-blocks" "quadrat" "skatepark" "geologist" "videomaker" "zoologist" )
this allows you to run `npm run build:all` from blockbase's folder, and that builds both the compiled CSS and theme.json files of all the children in the list. That means each time we update blockbase, the changes will propagate to all the children's theme.json files.

2021-10-13 09:44 UTC, scruffian commented on zoologist/theme-gen-readme.md
> +To create my-new-theme based on blank-canvas and
Should this say blockbase?

2021-10-13 09:44 UTC, scruffian commented on zoologist/theme-gen-readme.md
> +wp --require=wp-content/lib/theme-gen/init.php theme-gen fredricksonstarter.wordpress.com blank-canvas my-new-theme
Should this say blockbase?

2021-10-13 12:29 UTC, scruffian commented on zoologist/child-theme.json
> -					"size": "18px",
Done

2021-10-13 12:29 UTC, scruffian commented on zoologist/child-theme.json
> -					"size": "16px",
Done

2021-10-13 12:31 UTC, scruffian commented on zoologist/child-theme.json
> -					"fontWeight": 700,
Done

2021-10-13 12:33 UTC, scruffian commented on zoologist/child-theme.json
> -				"spacing": {
I'm not convinced this line does anything, it seems to be overridden by other rules:
<img width="665" alt="Screenshot 2021-10-13 at 13 33 19" src="https://user-images.githubusercontent.com/275961/137132995-30167a4a-aa95-4bff-8316-666879189bc1.png">

2021-10-13 12:40 UTC, scruffian commented
We should add a social nav too

2021-10-13 21:59 UTC, alaczek commented on zoologist/child-theme.json
> -				"spacing": {
What site is this screenshot from? On the Zoologist demo I see the spacing being added under post title:

![image](https://user-images.githubusercontent.com/4550351/137218362-ab324e33-8bf5-4911-9b74-036f2ebb3d37.png)

2021-10-13 22:30 UTC, scruffian commented on zoologist/child-theme.json
> -				"spacing": {
The screenshot is a local site running Gutenberg on trunk. I left the spacing config in the child-theme.json so I think this should be OK to merge?

2021-10-14 09:50 UTC, MaggieCabrera approved these changes
this LGTM!

2021-10-14 11:08 UTC, merged