Fix/pendant pattern meta
Automattic/themes pull request #5943
Opened 2022-04-26 17:21 UTC by pbking

Since the header isn't expected to be a pattern and there is nothing in it to localize this has been moved to the template instead.  (The footer, however, does have text to be localized so that remains a pattern, however it is hidden from the inserter).

The header was also refactored to be WIDE width instead of FULL width.  (I believe that was the original intent after looking at the designs more closely.  Please correct me if I'm mistaken.)

It now looks like this on very wide screens:

<img width="1906" alt="image" src="https://user-images.githubusercontent.com/146530/165355513-0463868f-e22f-41ea-8a9c-8d499485bf54.png">

The rest of the patterns available in the inserter are as follows:

<hr>

<img width="321" alt="image" src="https://user-images.githubusercontent.com/146530/165352408-77011142-b7ab-43c5-8277-bc35c26bc89f.png">

You [mentioned](https://github.com/Automattic/themes/issues/5884#issue-1208130435) not including this one, however if we don't make this available to users then the [Articles](PdS3dp-M-p2) page would be hard to build.

<hr>

<img width="327" alt="image" src="https://user-images.githubusercontent.com/146530/165355841-a10ae056-8d22-4dc5-9903-a9e0d204cd9a.png">

This one wasn't mentioned to include or not.  It was a complex bit to layout so including it as a pattern seems helpful.  LMK if you would rather me remove it from the inserter though.

<hr>

<img width="318" alt="image" src="https://user-images.githubusercontent.com/146530/165355947-12243c1e-926e-48b2-a104-65d029ebff83.png">

<hr>

<img width="316" alt="image" src="https://user-images.githubusercontent.com/146530/165355990-164ae5bd-5ce7-48e7-b9e6-991d23274a20.png">

<hr>

<img width="319" alt="image" src="https://user-images.githubusercontent.com/146530/165356031-5c7ae340-5a48-4798-bbfc-2e68fb03c1cf.png">

<hr>

<img width="321" alt="image" src="https://user-images.githubusercontent.com/146530/165356061-1f09e4f1-3d9e-49be-a1ee-4cff6303a9aa.png">

<hr>

<img width="323" alt="image" src="https://user-images.githubusercontent.com/146530/165356089-3a8118c2-6f76-4e66-a98e-d00cd464dcf8.png">

<hr>

<img width="322" alt="image" src="https://user-images.githubusercontent.com/146530/165356122-cebc5c99-57f5-4232-8bea-cd6f61a8a8ba.png">

<hr>

<img width="325" alt="image" src="https://user-images.githubusercontent.com/146530/165356145-227607c3-b167-4bea-a147-31ca04d718cb.png">

<hr>

At the moment ALL of the above patterns are exclusively in the 'Pendant' category.  Do we want to keep all of these in that category?  Some of them?

I assume we'll want to put them all into other categories (too) though.

I don't really know where they should go though...  Ideas?

Grid of Posts: Query
Latest Articles: Query
Home Page Hero: ?
Media & Text: ?
Image & Quote: ?
Gallery: Images
Our Picks: Images
Posts and Topics: ?
The Team: ?

2022-04-27 15:22 UTC, beafialho commented
> The header was also refactored to be WIDE width instead of FULL width. (I believe that was the original intent after looking at the designs more closely. Please correct me if I'm mistaken.)

Apologies as this may have been unclear and I missed it earlier: both the header and the footer should be full-width. I've [mocked up](https://www.figma.com/file/JdntsOfLqo8Vy0d5uTWHTI/Pendant?node-id=1858%3A71) what it should look like in a 2000px screen. Does that make sense?

![2000px](https://user-images.githubusercontent.com/65220155/165551538-ff97c7f6-57c3-4bab-90bf-6b26a68fb702.png)

> You https://github.com/Automattic/themes/issues/5884#issue-1208130435 not including this one, however if we don't make this available to users then the [Articles](https://github.com/Automattic/themes/pull/PdS3dp-M-p2) page would be hard to build.

Let's then keep the grid of posts and homepage hero pattern 👍 

> At the moment ALL of the above patterns are exclusively in the 'Pendant' category. Do we want to keep all of these in that category? Some of them?

I think it makes sense to keep them all in the Pendant category, except for the header and footer.

> I don't really know where they should go though... Ideas?

What do you think of these?

Home Page Hero: Call to Action
Media & Text: Media
Image & Quote: Quotes
Posts and Topics: List
The Team: List

2022-04-27 15:33 UTC, pbking commented
> Apologies as this may have been unclear and I missed it earlier: both the header and the footer should be full-width. I've [mocked up](JdntsOfLqo8Vy0d5uTWHTI-fi-1858%3A71) what it should look like in a 2000px screen. Does that make sense?

No apologies needed.  I should have clarified that earlier when I first had doubts.  That makes sense and I'm happy to oblige.

2022-04-27 17:09 UTC, pbking commented
Re-aligned:
![localhost_4759__p=9 (1)](https://user-images.githubusercontent.com/146530/165581566-0d501b22-318c-43fe-bc34-3b72490ac40d.png)

2022-04-28 09:12 UTC, madhusudhand requested changes

2022-04-28 09:12 UTC, madhusudhand commented on pendant/patterns/hero.php
> + * categories: pendant
I guess we are not adding theme based categories.
this can be `featured, text`

2022-04-28 09:12 UTC, madhusudhand commented on pendant/patterns/image-and-quote.php
>   */
featured, text, columns

2022-04-28 09:12 UTC, madhusudhand commented on pendant/patterns/image-gallery.php
> + * categories: pendant
featured, gallery

2022-04-28 09:12 UTC, madhusudhand commented on pendant/patterns/image-series.php
> + * categories: pendant
featured

2022-04-28 09:12 UTC, madhusudhand commented on pendant/patterns/media-and-text.php
>   * categories: pendant
featured, text

2022-04-28 09:12 UTC, madhusudhand commented on pendant/patterns/post-topics.php
> + * categories: pendant
featured, text

2022-04-28 09:14 UTC, madhusudhand commented
**other patterns**
Grid of Posts: query
Latest Articles: featured, query
Team: featured, columns

2022-04-28 09:20 UTC, madhusudhand commented on pendant/patterns/hero.php
> + * categories: pendant
posted summary of all patterns in PR comment.

2022-04-28 13:31 UTC, pbking commented on pendant/patterns/hero.php
> + * categories: pendant
Thank you, I have adjusted these based on both recommendations.

2022-04-28 13:33 UTC, pbking commented
I have adjusted the pattern categories based on the recommendations above.  'Pendant' has been replaced with 'Featured' and the other changes noted have been made (with a few exceptions).  'Columns' wasn't a used category that I could find so I haven't leveraged that one.

2022-04-28 13:34 UTC, merged