#5894: Blockbase: Fix comment subscription checkboxes
Automattic/themes pull request #6140
Opened 2022-06-24 17:13 UTC by bobmatyas

### Changes proposed in this Pull Request:

Adjust the grid for post comments on Blockbase to fix overlap issue that happens on Blockbase and children. I tested change on Blockbase, Dorna, and Winkel.

#### Before 
<img width="432" alt="Screenshot on 2022-06-24 at 11-23-18" src="https://user-images.githubusercontent.com/45246438/175609778-55f7c6c1-1607-4e3a-8ba2-fd51a516d09a.png">

#### After
<img width="482" alt="Screenshot on 2022-06-24 at 12-47-22" src="https://user-images.githubusercontent.com/45246438/175609783-393531c9-ffb4-4007-886e-0116fe5ae55f.png">

### Related issue(s):

Fixes #5894

2022-06-28 10:33 UTC, madhusudhand requested changes
1. run `npm run build` include the generated css changes.

2. I guess it is best to keep the checkboxes in the bottom after the button.
Following is how other themes block themes show the UI

<img width="310" alt="image" src="https://user-images.githubusercontent.com/1935113/176157966-3e365f6f-2418-4849-953e-845f8180e88f.png">

2022-06-28 10:36 UTC, MaggieCabrera commented
I think I'd rather go with https://github.com/Automattic/themes/pull/6109 as a solution instead, since it removes all the extra CSS from Blockbase and relies on the site editor instead.

2022-06-28 12:19 UTC, bobmatyas commented
I agree it seems like #6109 is a better way to go.

2022-07-14 14:58 UTC, vcanales commented
Closing, as the alternative PR (#6109) was merged.

2022-07-14 14:58 UTC, closed without merging