Assembler: Another round of tweaks (WIP)
Automattic/themes pull request #7602
Opened 2024-01-11 00:10 UTC by richtabor

2024-01-11 02:22 UTC, alaczek requested changes

2024-01-11 02:22 UTC, alaczek commented on assembler/templates/search.html
> +<p class="has-text-align-center">No search results.</p>
We should make this into a pattern to reuse across templates, and wrap this text in translation function.

2024-01-11 02:22 UTC, alaczek commented on assembler/templates/archive.html
> +<p class="has-text-align-center">No search results.</p>
We should make this into a pattern to reuse across templates, and wrap this text in translation function.

2024-01-11 02:22 UTC, alaczek commented on assembler/templates/404.html
> +<h2 class="wp-block-heading alignwide has-text-align-center" id="page-not-found">Page Not Found</h2>
We should make this into a pattern and wrap this text in translation function.

2024-01-11 02:59 UTC, alaczek commented
I reviewed the templates and have a few questions and comments:
1. Was there a specific reason to turn page with title into a pattern? 
2. Should we have some sort of post meta (date and author or category) in the single post template?
3. The post titles in archives and search templates look off:
 * some are centered, some are not
 * the line height is very tight
 * the font size is different than in index.html (which also has archive title - I think that's a bug?)
![image](https://github.com/Automattic/themes/assets/4550351/0d87b888-5bbe-413b-91e4-cd35a3b6dbc8)

2024-01-11 10:48 UTC, richtabor commented
Very strange about the centered titles. I'll take a look today.

2024-01-11 22:48 UTC, alaczek commented
This bit in theme.json forces the title to be centered:
```
"core/post-title": {
                "css": ":not([class*=\"text-align-\"]){text-align:center;}",
                "typography": {
                    "fontSize": "var(--wp--preset--font-size--x-large)"
                }
            },
```

2024-01-12 22:57 UTC, richtabor commented
I made all the requested changes; re-requesting a review + deployment. Thanks!

> Should we have some sort of post meta (date and author or category) in the single post template?

Let's revisit the blog design once the theme/assembler work is being tested and in flight.

2024-01-16 10:34 UTC, alaczek commented
> Let's revisit the blog design once the theme/assembler work is being tested and in flight.

Yep, agreed.

2024-01-16 10:34 UTC, merged