Margarethe: Add new theme
Automattic/themes pull request #8083
Opened 2024-09-06 09:05 UTC by MaggieCabrera

#### Changes proposed in this Pull Request:

#### Related issue(s):

2024-09-06 10:33 UTC, MaggieCabrera commented
This one is ready for review, it should be ready to submit to dotorg

2024-09-06 12:38 UTC, henriqueiamarino commented
@MaggieCabrera I checked the following items, and they are all LGTM:
- Templates and elements;
- Skip links;
- Hard-coded lines (with Theme Check)
- Readme file

I found only two topics that can be problematic:

Theme Check alerted us about these three images that can be compacted:
> WARNING: assets/images/margarethe-img-5-scaled.jpg is 590.1 KB in size. Large file sizes have a negative impact on website performance and loading time. Compress images before using them.
> WARNING: assets/images/margarethe-img-4-scaled.jpg is 591.0 KB in size. Large file sizes have a negative impact on website performance and loading time. Compress images before using them.
> WARNING: assets/images/margarethe-img-2-scaled.jpg is 767.5 KB in size. Large file sizes have a negative impact on website performance and loading time. Compress images before using them.

The Theme URI doesn't follow our standards. We have been using showcase pages on the Themeshaper site. So, this theme's page should be:
https://themeshaper.com/margarethe/

2024-09-11 00:53 UTC, alaczek requested changes, later dismissed
This looks good to me. The only thing I flagged is the size of some of the images - I don't know what's the recommended size, but I think anything over 350-400KB needs to be compressed.

2024-09-11 00:53 UTC, alaczek commented on margarethe/assets/images/margarethe-img-2-scaled.jpg
I think this image will have to be compressed.

2024-09-11 00:53 UTC, alaczek commented on margarethe/assets/images/margarethe-img-4-scaled.jpg
I think this image will have to be compressed.

2024-09-11 00:53 UTC, alaczek commented on margarethe/assets/images/margarethe-img-5-scaled.jpg
I think this image will have to be compressed.

2024-09-11 09:32 UTC, MaggieCabrera commented
I made the changes to the images and the theme URL, I'm bringing this in, thanks for the reviews!

2024-09-11 09:47 UTC, merged