Vows: fixes issues related to #8519
Automattic/themes pull request #8521
Opened 2024-12-13 06:47 UTC by henriqueiamarino

This PR fixes the issues mentioned in #8519. I also updated outdated presets that CBT used to apply. Now, the theme follows the standards we apply to all new themes.

2025-01-09 00:05 UTC, alaczek requested changes
This is looking good to me, except I don't see the Instrument Serif font used anywhere. If it's unused, please remove from the assets folder.

2025-01-13 11:53 UTC, henriqueiamarino commented
Thanks for getting this, @alaczek. I just removed the unused fonts.

2025-01-15 09:56 UTC, merged

2025-01-15 10:07 UTC, henriqueiamarino commented
@alaczek I merged it and tried to version bump it, but it didn't work. It's not the first time it has happened; I don't know what may be wrong with my setup. Can you please do it to me?

2025-01-21 20:08 UTC, iamtakashi commented
@henriqueiamarino It's probably that the theme with the fixes has already been deployed to Dotcom before you run the version bump workflow.

I manually bumped up the version here: https://github.com/Automattic/themes/pull/8614